# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 20 Apr 2026 08:13:36 +0200
*               @ALL          0
*               @user         8
