<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 27 Apr 2026 15:11:09 +0200
 */

$conf['title'] = '';
$conf['start'] = 'mirax';
$conf['lang'] = 'es';
$conf['template'] = 'mikio';
$conf['license'] = 'cc-by-sa';
$conf['camelcase'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['adhoctags']['allowedElements'] = 'b,aside,i,section,s,figure,u,figcaption,q,abbr,mark';
$conf['tpl']['mikio']['showLightDark'] = 1;
$conf['tpl']['mikio']['autoLightDark'] = 1;
$conf['tpl']['mikio']['navbarShowSub'] = 1;
$conf['tpl']['mikio']['tagsShowHero'] = 0;
$conf['tpl']['mikio']['footerPageInfoText'] = '[Powered by HAEDES]';
$conf['tpl']['bootstrap3']['hideInThemeSwitcher'] = 'darkly';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
