# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 20 Apr 2026 08:13:36 +0200
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$GuIcHU0UFwz0fZ8j4t7stuuI3EmjOGC6T2OdlVCE.CIdwIvFLW81W:Valery:valery.vallejo@haedes.eu:admin,user
